class_path: lightning.data.datamodules.Cars98NDataModule
init_args:
  data_dir: "/media/amidemo/Data/object_classifier_data/datasets"
  batch_size: 64
  train_transforms: lightning.data.default_transforms.Cars98NTrainTransforms
  val_transforms: lightning.data.default_transforms.Cars98NTestTransforms
  test_transforms: lightning.data.default_transforms.Cars98NTestTransforms
