model:
  init_args:
    noise_reducer_kwargs:
      strategy: torch_metric_learning.noise_reducers.sample_rejection.KNNPairRejection
      strategy_kwargs:
          k_neighbors: 10
          rejection_criteria: torch_metric_learning.noise_reducers.sample_rejection.HighestIsTheSame
          rejection_criteria_kwargs:
            threshold: null
          use_batched_knn: True
          with_relabel: True
          relabel_starting_epoch: 2
          relabel_confidence: 0.5
      keep_only_good_samples: False
      memory_size: 0
